module.exports = {
  apps: [
    {
      name: 'betterspend-api',
      namespace: 'betterspend',
      script: 'apps/api/dist/main.js',
      cwd: '/home/ubuntu/betterspend',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: 'postgresql://betterspend:betterspend@localhost:5433/betterspend',
        REDIS_URL: 'redis://localhost:6379',
        API_PORT: 4001,
        API_URL: 'http://147.135.36.170:4001',
        WEB_URL: 'http://147.135.36.170:3100',
      },
      log_file: '/home/ubuntu/.pm2/logs/betterspend-api.log',
      error_file: '/home/ubuntu/.pm2/logs/betterspend-api-error.log',
      out_file: '/home/ubuntu/.pm2/logs/betterspend-api-out.log',
      time: true,
      watch: false,
      max_memory_restart: '512M',
      restart_delay: 2000,
    },
    {
      name: 'betterspend-web',
      namespace: 'betterspend',
      script: 'node_modules/next/dist/bin/next',
      args: 'start',
      cwd: '/home/ubuntu/betterspend/apps/web',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3100,
        NEXT_PUBLIC_API_URL: 'http://147.135.36.170:4001',
      },
      log_file: '/home/ubuntu/.pm2/logs/betterspend-web.log',
      error_file: '/home/ubuntu/.pm2/logs/betterspend-web-error.log',
      out_file: '/home/ubuntu/.pm2/logs/betterspend-web-out.log',
      time: true,
      watch: false,
      max_memory_restart: '512M',
      restart_delay: 2000,
    },
  ],
};
